export const getStockMovement = () => `
    "merged_metadata": [
      "profit",
      "Return Sales Quantity",
      "total promotional sales",
      "inventory markups",
      "Sales Cost",
      "markdown cancel amount",
      "inventory clearance sales",
      "Clearance Sales Cost",
      "on hand inventory",
      "inventory return to vendor retail",
      "inventory_markups_cancel",
      "Item",
      "markups",
      "AUC",
      "district",
      "markdowns cancel",
      "Inventory Transfer Out Cost Amount",
      "inventory return to vendor cost",
      "markups cancel",
      "var",
      "Inventory Customer Reserved Quantity",
      "transfer ins",
      "Inventory Adjustment Cost Amount",
      "inventory status",
      "sub-category",
      "Inventory Transfer In Cost Amount",
      "rtv cost",
      "Banner Description",
      "Regular Sales Cost",
      "inventory_markup_cancel_quantity",
      "Inventory Markdown Quantity",
      "promotional sale",
      "transfer out quantity",
      "Date",
      "adjustment cost",
      "Channel ID",
      "Inventory Markup Cancel Quantity",
      "adjusted inventory retail",
      "inventory_markdowns_cancel",
      "average unit cost",
      "total promotional sales amount",
      "inventory adjustments",
      "inventory markdown cancel retail amount",
      "markdown retail amount",
      "gross profit",
      "regular margin",
      "YTD",
      "promotional sales",
      "month to date",
      "beginning on hand",
      "rtv inventory quantity",
      "Inventory Markup Cancel Amount",
      "Month To Date",
      "total discount amount",
      "chain",
      "total profit",
      "Area Description",
      "Inventory Markup Amount",
      "stock quantity",
      "transfer out retail",
      "class",
      "end on hand",
      "unit cost",
      "Net Sales",
      "return sales",
      "Group ID",
      "Division ID",
      "adjustment retail",
      "net sales",
      "clearance margin",
      "sales quantity",
      "adjusted quantity",
      "return to vendor cost",
      "inventory adjusted quantity",
      "Inventory Intransit Quantity",
      "boh",
      "negative pos",
      "stock clearance sales",
      "net var",
      "total regular profit",
      "Inventory Markdown Cancel Quantity",
      "Chain ID",
      "variance",
      "Inventory RTV Cost Amount",
      "subclass",
      "inventory on hand retail amount",
      "on hand retail",
      "inventory adjusted cost",
      "onhands",
      "return to vendor quantity",
      "Gross Margin Percentage",
      "inventory markup quantity",
      "MTD",
      "markdown cancel retail amount",
      "Geozone ID",
      "Nisan Shrestha",
      "Inventory BOH Cost Amount",
      "Inventory Intransit Cost Amount",
      "VAT Amount",
      "Inventory Type",
      "sales@retail",
      "Department ID",
      "inventory transit quantity",
      "inventory_positions",
      "rtv inventory cost",
      "inventory rtv retail",
      "inventory markup retail_amount",
      "onhands inventory",
      "Division Description",
      "return to vendor retail",
      "District ID",
      "transfer in quantity",
      "Inventory Onorder Quantity",
      "Inventory Receipt Retail Amount",
      "inventory adjustment retail",
      "Regular Sales Quantity",
      "Inventory Adjustment Quantity",
      "location",
      "Promotional Sales Quantity",
      "stock to sales ratio",
      "Inventory BOH Retail Amount",
      "net variance",
      "stock on hand retail",
      "Class ID",
      "Inventory Non Sellable Quantity",
      "net clearance sales quantity",
      "store",
      "transfer out cost",
      "transfer outs",
      "Subclass ID",
      "Inventory Onorder Cost Amount",
      "Inventory Markdown Amount",
      "Inventory Markdown Cancel Amount",
      "group",
      "total sales",
      "adjustments",
      "sales retail",
      "total clearance profit",
      "transfer in retail",
      "inventory adjustment quantity",
      "Location Description",
      "regular profit",
      "department",
      "category",
      "Total Discount Amount",
      "inventory rtv cost",
      "Inventory Transfer Out Quantity",
      "sales",
      "Inventory BOH Quantity",
      "total promotional profit",
      "inventory adjustment cost",
      "Inventory Intransit Retail Amount",
      "net discount amount",
      "net clearance profit",
      "negative purchases",
      "discount amount",
      "inventory rtv quantity",
      "loss",
      "inventory on hand",
      "markup quantity",
      "markup retail amount",
      "inventory in transit",
      "Class Description",
      "net clearance sales amount",
      "inventory markdowns",
      "Subclass Description",
      "Item Description",
      "total margin",
      "product",
      "inventory markdown cancel quantity",
      "Department Description",
      "Inventory Onhand Quantity",
      "rtv retail",
      "Area ID",
      "ashok budha",
      "Inventory Transfer In Retail Amount",
      "promotional margin",
      "Clearance Sales Quantity",
      "rtvs",
      "markup cancel quantity",
      "Group Description",
      "rtv",
      "stock on hand retail amount",
      "total adjustments",
      "Region Description",
      "on hand quantity",
      "return to vendors",
      "gross margin percentage",
      "average net retail",
      "contribution",
      "Inventory Transfer Reserved Quantity",
      "stock on hand cost amount",
      "transfer in cost",
      "markdown amount",
      "Inventory Markup Quantity",
      "Inventory Receipt Quantity",
      "negative purchase orders",
      "adjusted cost",
      "Return Sales Cost",
      "Regular Sales Amount",
      "inventories",
      "Inventory Receipt Cost Amount",
      "District Description",
      "eoh",
      "AUR",
      "inventory markdown quantity",
      "on hands",
      "Return Sales Amount",
      "sales value",
      "inventory markdown retail amount",
      "adjusted retail amount",
      "Geozone Description",
      "Promotional Sales Amount",
      "Inventory Onhand Cost Amount",
      "adjusted retail",
      "rtv quantity",
      "inventory return to vendor quantity",
      "Sales Amount",
      "markup cancel amount",
      "inventory transfers",
      "clearance profit",
      "adjusted inventory quantity",
      "Inventory Onhand Retail Amount",
      "Net sales",
      "sales@Nisan",
      "inventory adjustmen retail",
      "average unit retail",
      "adjusted inventory cost",
      "stock on hand cost",
      "markdown_quantity",
      "Inventory Adjustment Retail Amount",
      "Channel Description",
      "on hand cost",
      "division",
      "cogs",
      "Clearance Sales Amount",
      "Employee Discount Amount",
      "promotional profit",
      "Gross Margin %",
      "Banner ID",
      "inventory on hand retail",
      "Inventory Transfer Out Retail Amount",
      "cost of goods sold",
      "inventory positions",
      "margin",
      "Sales Quantity",
      "region",
      "area",
      "in transit quantity",
      "Inventory Onorder Retail Amount",
      "Gross Margin",
      "merchandise",
      "transfers",
      "on order quantity",
      "Location ID",
      "rtv inventory retail",
      "Inventory RTV Quantity",
      "Margin %",
      "regular cost",
      "markup cancel retail amount",
      "Chain Description",
      "clearance sales",
      "aur",
      "Inventory Transfer In Quantity",
      "Inventory RTV Retail Amount",
      "Region ID",
      "employee discount amount",
      "net employee discount",
      "regular sales",
      "year to date",
      "inventory on hand cost",
      "inventory on hand cost amount",
      "markdowns",
      "markdown cancel quantity",
      "auc",
      "Promotional Sales Cost",
      "markup amount"
    ]
`;
